from flask import Flask, render_template, request
import json
import plotly
from plotly import graph_objs as go
import numpy as np
import pandas as pd

app = Flask(__name__)


def get_about():
    about = "I WAS GENERATED BY PYTHON INTO HTML"
    return about


def create_plot(value):
    try:
        N = int(value)
    except ValueError:
        N = 40
    x = np.random.uniform(low=0, high=10, size=(N, ))
    y = np.random.uniform(low=0, high=10, size=(N, ))
    df = pd.DataFrame({'x': x, 'y': y})

    data = [
        go.Scatter(
            x=df['x'],
            y=df['y'],
            mode='markers')
    ]

    layout = go.Layout(
        yaxis={'title': 'X'},
        xaxis={'title': 'Y'},
        margin={'l': 50, 'r': 50, 'b': 50, 't': 20, 'pad': 0}
    )

    figure = dict(data=data, layout=layout)
    graphJSON = json.dumps(figure, cls=plotly.utils.PlotlyJSONEncoder)

    return graphJSON


@app.route('/', methods=['GET', 'POST'])
def updated_index():
    arg_1 = request.form['user_input']
    bar = create_plot(arg_1)
    about = get_about()
    return render_template('index.html', plot=bar, about=about)


# @app.route('/')
# def index():
#     text = 40
#     bar = create_plot(text)
#     return render_template('index.html', plot=bar)

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0')
